---
version: '3'
volumes:
  sbt-cache:
  ivy2-cache:
  cache:
services:
  elements:
    build: .
    image: elements:v1.0
    container_name: i2c-gpio-expander_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /home:/home
      - ivy2-cache:/root/.ivy2
      - sbt-cache:/root/.sbt
      - cache:/root/.cache
    command: ["sleep", "infinity"]
