# SPDX-FileCopyrightText: 2025 aesc silicon
#
# SPDX-License-Identifier: CERN-OHL-W-2.0

---
version: '3'
volumes:
  sbt-cache:
  ivy2-cache:
  cache:
services:
  elements:
    image: docker.io/dnltz/elements:v2.0
    container_name: i2c-gpio-expander_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /home:/home
      - ivy2-cache:/root/.ivy2
      - sbt-cache:/root/.sbt
      - cache:/root/.cache
    command: ["sleep", "infinity"]
