name: Check Design Flow from RTL to GDS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo snap install task --classic
        sudo apt install virtualenv

    - name: Prepare the project
      run: |
        task install branch=${{ github.head_ref || 'main' }}

    - name: Prepare files
      run: |
        IS_HEADLESS=true task prepare

    - name: Generate layout
      run: |
        IS_HEADLESS=true task layout

    - name: Add metal fill
      run: |
        IS_HEADLESS=true task filler

    - name: RUN maximal DRC
      run: |
        IS_HEADLESS=true task run-drc
